-- liquibase formatted sql
-- changeset Vasiliy:1

DROP TABLE IF EXISTS sensors CASCADE;

CREATE TABLE sensors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(30) NOT NULL,
    model VARCHAR(15) NOT NULL,
    range_from INTEGER NOT NULL,
    range_to INTEGER NOT NULL,
    type VARCHAR(255) NOT NULL,
    unit VARCHAR(255),
    location VARCHAR(40),
    description VARCHAR(200)
);

INSERT INTO sensors (name, model, range_from, range_to, type, unit, location, description)
VALUES
    ('Barometer1', 'bb-10', 22, 45, 'PRESSURE', 'BAR', 'kitchen', 'Первый барометр'),
    ('Barometer2', 'bb-20', 10, 30, 'PRESSURE', 'BAR', 'garage', 'Второй барометр'),
    ('Thermometer1', 'tt-30', 0, 100, 'TEMPERATURE', 'CELSIUS', 'room', 'Первый термометр'),
    ('Thermometer2', 'tt-40', 20, 50, 'TEMPERATURE', 'CELSIUS', 'basement', 'Второй термометр'),
    ('Hygrometer1', 'hh-50', 10, 90, 'HUMIDITY', 'PERCENT', 'bathroom', 'Первый гидрометр'),
    ('Hygrometer2', 'hh-60', 20, 80, 'HUMIDITY', 'PERCENT', 'living room', 'Второй гидрометр'),
    ('Voltmeter1', 'vv-70', 0, 220, 'VOLTAGE', 'VOLTAGE', 'office', 'Первый вольтометр'),
    ('Voltmeter2', 'vv-80', 100, 300, 'VOLTAGE', 'VOLTAGE', 'workshop', 'Второй вольтометр');